"""Config file writer for the Setup Wizard.

Writes config.yaml as a minimal working configuration and updates .env
without wiping existing user customisations where possible.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


# ── .env helpers ──────────────────────────────────────────────────────────────

def read_env_file(env_path: Path) -> dict[str, str]:
    """Parse a .env file into a dict (ignores comments and blank lines)."""
    result: dict[str, str] = {}
    if not env_path.exists():
        return result
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    return result


def write_env_file(env_path: Path, pairs: dict[str, str]) -> None:
    """Merge *pairs* into an existing (or new) .env file.

    Existing keys are updated in place; new keys are appended.
    Lines with comments and other formatting are preserved.
    """
    lines: list[str] = []
    if env_path.exists():
        lines = env_path.read_text(encoding="utf-8").splitlines()

    updated: set[str] = set()
    new_lines: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in pairs:
                new_lines.append(f"{key}={pairs[key]}")
                updated.add(key)
                continue
        new_lines.append(line)

    for key, value in pairs.items():
        if key not in updated:
            new_lines.append(f"{key}={value}")

    env_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")


# ── config.yaml helpers ───────────────────────────────────────────────────────

def _yaml_dump(data: Any) -> str:
    return yaml.safe_dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)


def build_minimal_config(
    *,
    provider_use: str,
    model_name: str,
    display_name: str,
    api_key_field: str,
    env_var: str,
    extra_model_config: dict | None = None,
    base_url: str | None = None,
    search_use: str | None = None,
    search_tool_name: str = "web_search",
    config_version: int = 5,
) -> str:
    """Build the content of a minimal config.yaml."""
    from datetime import date

    today = date.today().isoformat()

    model_entry: dict[str, Any] = {
        "name": "default",
        "display_name": display_name,
        "use": provider_use,
        "model": model_name,
        api_key_field: f"${env_var}",
    }
    if base_url:
        model_entry["base_url"] = base_url
    if extra_model_config:
        model_entry.update(extra_model_config)

    data: dict[str, Any] = {
        "config_version": config_version,
        "models": [model_entry],
    }

    tools: list[dict[str, Any]] = [
        {"name": "ls", "use": "deerflow.sandbox.tools:ls_tool", "group": "sandbox"},
        {"name": "read_file", "use": "deerflow.sandbox.tools:read_file_tool", "group": "sandbox"},
        {"name": "glob", "use": "deerflow.sandbox.tools:glob_tool", "group": "sandbox"},
        {"name": "grep", "use": "deerflow.sandbox.tools:grep_tool", "group": "sandbox"},
        {"name": "write_file", "use": "deerflow.sandbox.tools:write_file_tool", "group": "sandbox"},
        {"name": "str_replace", "use": "deerflow.sandbox.tools:str_replace_tool", "group": "sandbox"},
        {"name": "bash", "use": "deerflow.sandbox.tools:bash_tool", "group": "sandbox"},
        {"name": "image_search", "use": "deerflow.community.image_search.tools:image_search_tool", "group": "search"},
    ]

    if search_use:
        search_tool: dict[str, Any] = {
            "name": search_tool_name,
            "use": search_use,
            "group": "search",
        }
        tools.insert(0, search_tool)

    data["tools"] = tools
    data["sandbox"] = {"use": "deerflow.sandbox.local:LocalSandboxProvider"}

    header = (
        f"# DeerFlow Configuration\n"
        f"# Generated by 'make setup' on {today}\n"
        f"# Run 'make setup' to reconfigure, or edit this file for advanced options.\n"
        f"# Full reference: config.example.yaml\n\n"
    )

    return header + _yaml_dump(data)


def write_config_yaml(
    config_path: Path,
    *,
    provider_use: str,
    model_name: str,
    display_name: str,
    api_key_field: str,
    env_var: str,
    extra_model_config: dict | None = None,
    base_url: str | None = None,
    search_use: str | None = None,
    search_tool_name: str = "web_search",
) -> None:
    """Write (or overwrite) config.yaml with a minimal working configuration."""
    # Read config_version from config.example.yaml if present
    config_version = 5
    example_path = config_path.parent / "config.example.yaml"
    if example_path.exists():
        try:
            import yaml as _yaml
            raw = _yaml.safe_load(example_path.read_text(encoding="utf-8")) or {}
            config_version = int(raw.get("config_version", 5))
        except Exception:
            pass

    content = build_minimal_config(
        provider_use=provider_use,
        model_name=model_name,
        display_name=display_name,
        api_key_field=api_key_field,
        env_var=env_var,
        extra_model_config=extra_model_config,
        base_url=base_url,
        search_use=search_use,
        search_tool_name=search_tool_name,
        config_version=config_version,
    )
    config_path.write_text(content, encoding="utf-8")
